### PR TITLE
fix: export spinner function from utils prompt

### PR DESCRIPTION
**Pull request by m0nch1**
### 🔗 Linked issue

issue: https://github.com/unjs/consola/issues/284

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Use spinner in examples/spinner.ts, prompt.ts

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### note 
Result of local run...

https://github.com/unjs/consola/assets/26811986/b1bf45b1-f5fd-4ca9-bde9-60700a56e017

### CODE REVIEW

**Comment by adesombergh** [comment]
Changing the examples does not fix the issue. Running `consola.start()`, `await new Promise((resolve) => setTimeout(resolve, 1000));`, `consola.success()` will still not show an animated spinner as expected.

**Comment by m0nch1** [comment]
@adesombergh 
In the current implementation, consola.start does not have a spinner function, and the spinner is defined in utils/prompt.ts

And my PR only works with spinner in example, so there is no way to actually import consola and use it...

I think this needs to be implemented so that spinner can work with prompt...

**Comment by m0nch1** [comment]
I tried to make spinner available from utils!

**Comment by m0nch1** [comment]
@Atinux @adesombergh 
What do you think of this?
I'm sure spinner is not used yet, and maybe it's okay to not support it, once it is!

**Comment by AndreaPontrandolfo** [comment]
Whats blocking this? The fact that the spinner is static make console.start practically useless

**Comment by pi0** [comment]
Thanks for PR, moving work to #333 (we need to integrate it to core and lazy import only for default build/ fancy output with fallback.)

**Pull request closed without merging**
