### PR TITLE
feat: support report error `cause`

### PR DESCRIPTION
**Pull request by kongmoumou**
The `cause` property of Error had been support in [most runtime](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#browser_compatibility) and been widely adapted by many repo.

The Chrome devtool already support showing caused error like screenshot below ⬇️

image

This PR support report error cause to console while used in node. Related issue #202 

image

Test code provided:

```ts
import { consola } from "./src/index";

consola.error(
  new Error("This is an error", {
    cause: new Error("This is the cause", {
      cause: new Error("This is the cause of the cause"),
    }),
  }),
);

```

### CODE REVIEW

**Comment by DrJume** [comment]
This would be so good to have! The cause adds important context in many errors (e.g. fetch errors with undici).
I didn't know that consola hides it and lost some time because of it, because I didn't get all information from the error.

**Comment by kongmoumou** [comment]
@ pi0 Could you let me know any progress of this feat? Looking forward to ur thought~ 😂

**Comment by pi0** [comment]
@kongmoumou it is on my list sorry got delayed (i might need to push small refactors before)

**Comment by pi0** [comment]
Thanks again and sorry it got delayed. I made few refactors + it is more consistent with Node.js stacks now:

image

**Pull request merged**
